use_frameworks!

platform :ios, '9.0'

target 'JHCCommonUtil_Example' do
  pod 'JHCCommonUtil', :path => '../'

  target 'JHCCommonUtil_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
